### ISSUE TITLE
发动态，报403错误，说没有权限发布动态

### ISSUE THREAD

**Issue by kuse2001** [slimkit/plus-component-feed#6]
![image](https://user-images.githubusercontent.com/12782761/30526620-2c904dfc-9c50-11e7-88f8-54381b2db2c0.png)

是什么原因呢

**Comment by this-BaiShi** [comment]
进入后台 在相应的用户组里增加一下发布动态的权限

**Comment by kuse2001** [comment]
![image](https://user-images.githubusercontent.com/12782761/30571790-958b2a4e-9d1c-11e7-9a42-95890b5c4a04.png)



该设置的都设了，好像也没有发布动态的权限，是否因为feed组件没装好的关系 [https://github.com/slimkit/plus-component-h5/issues/105](url)

**Comment by this-BaiShi** [comment]
应该是没有运行动态权限相关的迁移，可以参考这个扩展包里的/database/seeds/FeedAbilitySeeder.php 这个文件，里面其实只定义了几个很简单的权限
