### ISSUE TITLE
install feed error

### ISSUE THREAD

**Issue by xiaoke1989** [slimkit/plus-component-feed#7]
vagrant@homestead:~/Code/thinksns$ php artisan package:handle feed resolve
Copied Directory [/vendor/zhiyicx/plus-component-feed/assets] To [/public/zhiyicx/plus-component-feed]
Publishing complete.
Nothing to migrate.

 Run seeder (yes/no) [no]:
 > yes

Seeding: FeedPermissionSeeder

                                                           
  [Symfony\Component\Debug\Exception\FatalThrowableError]  
  Class 'Zhiyi\Plus\Models\Permission' not found

**Comment by medz** [comment]
Resolved, run the `composer update` and run the feed install command.
